# Site
name: "Guitar Tuner"
description: "Mundana is a free Jekyll theme for awesome people like you, Medium like."
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
baseurl: ""
email: ""
mailchimp-list: "https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b"
comments: false

include: ["_pages"]
permalink: /:slug

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    category: "/category/:name/"
    tag: "/tag/:name/"

authors:
  sal:
    name: Sal
    site: https://www.wowthemes.net
    avatar: assets/images/avatar1.jpg
    bio: "Hi, I am Sal, rddw author of Mundana, the theme you're currently previewing. I hope you like it!"
    email: wowthemesnet@gmail.com
    twitter: https://twitter.com/wowthemesnet

  jane:
    name: Jane
    site: https://www.wowthemes.net
    avatar: assets/images/avatar2.jpg
    bio: "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
    email: fakemail@gmail.com
    twitter: https://twitter.com/wowthemesnet

# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
  [
    README.markdown,
    package.json,
    grunt.js,
    Gruntfile.js,
    Gruntfile.coffee,
    node_modules,
  ]

sitemap:
  enabled: false
