name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change this to your default branch if necessary

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Ruby
      # - name: Set up Ruby
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: 3.1 # Use the Ruby version compatible with your project
      #     bundler-cache: true

      # Step 2: Pull the custom Docker image
      - name: Pull custom Jekyll build image
        run: |
          docker pull ghcr.io/actions/jekyll-build-pages:v1.0.13

      # Step 4: Build the Jekyll site with `JEKYLL_ENV=production`
      - name: Build Jekyll site
        uses: actions/jekyll-build-pages@v1
        with:
          source: .
          destination: ./_site
          future: false
          verbose: true
          token: ${{ secrets.GITHUB_TOKEN }}
          build_revision: ${{ github.sha }}
        env:
          JEKYLL_ENV: production

      # Step 5: Deploy to GitHub Pages
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site
          name: github-pages
          retention-days: 1

      # Step 6: Archive the artifact and upload it
      - name: Archive artifact and upload
        run: |
          echo "::group::Archive artifact"
          tar \
            --dereference --hard-dereference \
            --directory "$INPUT_PATH" \
            -cvf "$RUNNER_TEMP/artifact.tar" \
            --exclude=.git \
            --exclude=.github \
            .
          echo "::endgroup::"
        env:
          INPUT_PATH: ./_site

      - name: Generate Archives
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: /home/runner/work/_temp/artifact.tar
          sretention-days: 1
          if-no-files-found: error
          compression-level: 6
          overwrite: false
          include-hidden-files: false

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          timeout: 600000
          error_count: 10
          reporting_interval: 5000
          artifact_name: github-pages
          preview: false
